### ISSUE TITLE
Live Twitch streams fail to transcode

### ISSUE THREAD

**Issue by dcflachs** [fe80Grau/ytdlp2STRM#10]
I keep running into an issue with live Twitch streams. Many live streams that show an ad at the beginning fail to work. The streams start ok initially playing the "Commercial Break in progress" screen but after that there is only black. Grabbing the stream directly in VLC works fine but through jellyfin not so much. The ffmpeg transcode log for the session shows an error like this. 

`[mpegts @ 0x5628b2994540] Packet corrupt (stream = 1, dts = 6748380).
[hls @ 0x5628b268a6c0] Packet corrupt (stream = 1, dts = 6745320).
http://127.0.0.1:5000/twitch/direct/Mousie@40904378728: corrupt input packet in stream 1
frame=  449 fps= 32 q=11.0 size=N/A time=00:00:13.03 bitrate=N/A speed=0.926x    
More than 1000 frames duplicated`

**Comment by dcflachs** [comment]
I have observed the issue on the following channels "PotasticP", "bouphe", "Mousie", "tarik", "xQc". So far as i can tell its actually any channel that begins with a commercial.  

As I mentioned, tuning into the stream url (via ytdlp2STRM) with VLC plays the stream fine showing the commercial break screen and then eventually the stream. It is only the jellyfin transcoder that seems to have a problem with it, and only after the commercial break screen. I have tried various transcoder settings to see if that had something to do with it but they all behave the same.

**Comment by MLuehn** [comment]
Hey, any Updates? Same error here...

**Comment by fe80Grau** [comment]
Jellyfin web issue. Maybe fixed in the last Jellyfin release.

**Comment by dcflachs** [comment]
@fe80Grau This issue still exists in the latest jellyfin release. Best I have been able to discern it is not a issue with Jellyfin Web but with the Jellyfin Server HLS handling. If i understand correctly jellyfin passes the m3u playlist decoding off to FFMPEG which is unable to correctly handle the #EXT-X-DISCONTINUITY tags used to embed ads into some Twitch Live streams.
